on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    needs: build
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.yaml"
      output_folder: "keymap-drawer"
      parse_args: ""
      draw_args: ""
      commit_message: "[Draw] Update keymap images"
