on: [push, pull_request, workflow_dispatch]

jobs:
  build-standard:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: build-standard.yaml
      archive_name: firmware-standard

  build-hybrid:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: build-hybrid.yaml
      archive_name: firmware-hybrid

  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.yaml"
      output_folder: "keymap-drawer"
      parse_args: ""
      draw_args: ""
      commit_message: "[Draw] Update keymap images"
